<?php
/**
 * Ffm_Holidaythemes extension.
 *
 *              *
 *             /.\
 *            /..'\
 *           /'.'.'\
 *          /.''.''.\
 *         /.'.'.'.'.\
 *  "'""""/'.''.'.''.'\""'"'"
 *        ^^^^[_]^^^^^^
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the OSL 3.0 License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/OSL-3.0
 *
 * @package       Ffm_Holidaythemes
 * @copyright      Copyright (c) 2016
 * @license        OSL 3.0 http://opensource.org/licenses/OSL-3.0
 */
/**
 * Template to inject misc html snippets for theming
 *
 * @category    Ffm_Holidaythemes
 * @author      Sander Mangel <s.mangel@fitforme.nl>
*/

/** @var Ffm_Holidaythemes_Block_Adminhtml_Overlay $this */
?>
<?php if ($this->showTheme('snow2016')):?>
<link href="https://fonts.googleapis.com/css?family=Mountains+of+Christmas" rel="stylesheet"/>
<div id="holidaythemes-overlay" class="snow" style="display:block;">
    <i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i>
    <i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i>
    <i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i>
    <i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i>

    <div class="message">
        Happy Holidays! <br/>
        <a href="<?php echo $this->getToggleUrl('snow2016');?>">turn off</a>
    </div>
</div>
<?php endif;?>

